name: Test

on: [push]

jobs:
  jvm:
    name: Test JVM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - uses: coursier/cache-action@v6
      - name: Test
        run: sbt vyxalJVM/test

  native:
    name: Test Native
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - uses: coursier/cache-action@v6
      - name: Test
        run: sbt vyxalNative/test

  js:
    name: Compile JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - uses: coursier/cache-action@v6
      - name: Compile
        run: sbt vyxalJS/compile
      - name: Link
        run: sbt vyxalJS/fastLinkJS
      - name: Upload JS
        uses: actions/upload-artifact@v3.1.3
        with:
          name: js
          path: js/target/scala-3.3.0/vyxal-fastopt/
          
